spring:
  application:
    name: expenify

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
